/*
  # Insert Counties - Batch 2 (Georgia through Massachusetts)

  1. Data
    - Georgia (159 counties)
    - Idaho (44 counties)
    - Illinois (102 counties)
    - Indiana (92 counties)
    - Iowa (99 counties)
    - Kansas (105 counties)
    - Louisiana (64 parishes)
    - Maine (16 counties)
    - Maryland (24 counties)
    - Massachusetts (14 counties)
*/

INSERT INTO counties (name, state_code, is_active) VALUES
-- Georgia (159 counties)
('Appling', 'GA', true),('Atkinson', 'GA', true),('Bacon', 'GA', true),('Baker', 'GA', true),('Baldwin', 'GA', true),
('Banks', 'GA', true),('Barrow', 'GA', true),('Bartow', 'GA', true),('Ben Hill', 'GA', true),('Berrien', 'GA', true),
('Bibb', 'GA', true),('Bleckley', 'GA', true),('Brantley', 'GA', true),('Brooks', 'GA', true),('Bryan', 'GA', true),
('Bulloch', 'GA', true),('Burke', 'GA', true),('Butts', 'GA', true),('Calhoun', 'GA', true),('Camden', 'GA', true),
('Candler', 'GA', true),('Carroll', 'GA', true),('Catoosa', 'GA', true),('Charlton', 'GA', true),('Chatham', 'GA', true),
('Chattahoochee', 'GA', true),('Chattooga', 'GA', true),('Cherokee', 'GA', true),('Clarke', 'GA', true),('Clay', 'GA', true),
('Clayton', 'GA', true),('Clinch', 'GA', true),('Cobb', 'GA', true),('Coffee', 'GA', true),('Colquitt', 'GA', true),
('Columbia', 'GA', true),('Cook', 'GA', true),('Coweta', 'GA', true),('Crawford', 'GA', true),('Crisp', 'GA', true),
('Dade', 'GA', true),('Dawson', 'GA', true),('Decatur', 'GA', true),('DeKalb', 'GA', true),('Dodge', 'GA', true),
('Dooly', 'GA', true),('Dougherty', 'GA', true),('Douglas', 'GA', true),('Early', 'GA', true),('Echols', 'GA', true),
('Effingham', 'GA', true),('Elbert', 'GA', true),('Emanuel', 'GA', true),('Evans', 'GA', true),('Fannin', 'GA', true),
('Fayette', 'GA', true),('Floyd', 'GA', true),('Forsyth', 'GA', true),('Franklin', 'GA', true),('Fulton', 'GA', true),
('Gilmer', 'GA', true),('Glascock', 'GA', true),('Glynn', 'GA', true),('Gordon', 'GA', true),('Grady', 'GA', true),
('Greene', 'GA', true),('Gwinnett', 'GA', true),('Habersham', 'GA', true),('Hall', 'GA', true),('Hancock', 'GA', true),
('Haralson', 'GA', true),('Harris', 'GA', true),('Hart', 'GA', true),('Heard', 'GA', true),('Henry', 'GA', true),
('Houston', 'GA', true),('Irwin', 'GA', true),('Jackson', 'GA', true),('Jasper', 'GA', true),('Jeff Davis', 'GA', true),
('Jefferson', 'GA', true),('Jenkins', 'GA', true),('Johnson', 'GA', true),('Jones', 'GA', true),('Lamar', 'GA', true),
('Lanier', 'GA', true),('Laurens', 'GA', true),('Lee', 'GA', true),('Liberty', 'GA', true),('Lincoln', 'GA', true),
('Long', 'GA', true),('Lowndes', 'GA', true),('Lumpkin', 'GA', true),('Macon', 'GA', true),('Madison', 'GA', true),
('Marion', 'GA', true),('McDuffie', 'GA', true),('McIntosh', 'GA', true),('Meriwether', 'GA', true),('Miller', 'GA', true),
('Mitchell', 'GA', true),('Monroe', 'GA', true),('Montgomery', 'GA', true),('Morgan', 'GA', true),('Murray', 'GA', true),
('Muscogee', 'GA', true),('Newton', 'GA', true),('Oconee', 'GA', true),('Oglethorpe', 'GA', true),('Paulding', 'GA', true),
('Peach', 'GA', true),('Pickens', 'GA', true),('Pierce', 'GA', true),('Pike', 'GA', true),('Polk', 'GA', true),
('Pulaski', 'GA', true),('Putnam', 'GA', true),('Quitman', 'GA', true),('Rabun', 'GA', true),('Randolph', 'GA', true),
('Richmond', 'GA', true),('Rockdale', 'GA', true),('Schley', 'GA', true),('Screven', 'GA', true),('Seminole', 'GA', true),
('Spalding', 'GA', true),('Stephens', 'GA', true),('Stewart', 'GA', true),('Sumter', 'GA', true),('Talbot', 'GA', true),
('Taliaferro', 'GA', true),('Tattnall', 'GA', true),('Taylor', 'GA', true),('Telfair', 'GA', true),('Terrell', 'GA', true),
('Thomas', 'GA', true),('Tift', 'GA', true),('Toombs', 'GA', true),('Towns', 'GA', true),('Treutlen', 'GA', true),
('Troup', 'GA', true),('Turner', 'GA', true),('Twiggs', 'GA', true),('Union', 'GA', true),('Upson', 'GA', true),
('Walker', 'GA', true),('Walton', 'GA', true),('Ware', 'GA', true),('Warren', 'GA', true),('Washington', 'GA', true),
('Wayne', 'GA', true),('Webster', 'GA', true),('Wheeler', 'GA', true),('White', 'GA', true),('Whitfield', 'GA', true),
('Wilcox', 'GA', true),('Wilkes', 'GA', true),('Wilkinson', 'GA', true),('Worth', 'GA', true),
-- Idaho (44 counties)
('Ada', 'ID', true),('Adams', 'ID', true),('Bannock', 'ID', true),('Bear Lake', 'ID', true),('Benewah', 'ID', true),
('Bingham', 'ID', true),('Blaine', 'ID', true),('Boise', 'ID', true),('Bonner', 'ID', true),('Bonneville', 'ID', true),
('Boundary', 'ID', true),('Butte', 'ID', true),('Camas', 'ID', true),('Canyon', 'ID', true),('Caribou', 'ID', true),
('Cassia', 'ID', true),('Clark', 'ID', true),('Clearwater', 'ID', true),('Custer', 'ID', true),('Elmore', 'ID', true),
('Franklin', 'ID', true),('Fremont', 'ID', true),('Gem', 'ID', true),('Gooding', 'ID', true),('Idaho', 'ID', true),
('Jefferson', 'ID', true),('Jerome', 'ID', true),('Kootenai', 'ID', true),('Latah', 'ID', true),('Lemhi', 'ID', true),
('Lewis', 'ID', true),('Lincoln', 'ID', true),('Madison', 'ID', true),('Minidoka', 'ID', true),('Nez Perce', 'ID', true),
('Oneida', 'ID', true),('Owyhee', 'ID', true),('Payette', 'ID', true),('Power', 'ID', true),('Shoshone', 'ID', true),
('Teton', 'ID', true),('Twin Falls', 'ID', true),('Valley', 'ID', true),('Washington', 'ID', true),
-- Illinois (102 counties)
('Adams', 'IL', true),('Alexander', 'IL', true),('Bond', 'IL', true),('Boone', 'IL', true),('Brown', 'IL', true),
('Bureau', 'IL', true),('Calhoun', 'IL', true),('Carroll', 'IL', true),('Cass', 'IL', true),('Champaign', 'IL', true),
('Christian', 'IL', true),('Clark', 'IL', true),('Clay', 'IL', true),('Clinton', 'IL', true),('Coles', 'IL', true),
('Cook', 'IL', true),('Crawford', 'IL', true),('Cumberland', 'IL', true),('DeKalb', 'IL', true),('De Witt', 'IL', true),
('Douglas', 'IL', true),('DuPage', 'IL', true),('Edgar', 'IL', true),('Edwards', 'IL', true),('Effingham', 'IL', true),
('Fayette', 'IL', true),('Ford', 'IL', true),('Franklin', 'IL', true),('Fulton', 'IL', true),('Gallatin', 'IL', true),
('Greene', 'IL', true),('Grundy', 'IL', true),('Hamilton', 'IL', true),('Hancock', 'IL', true),('Hardin', 'IL', true),
('Henderson', 'IL', true),('Henry', 'IL', true),('Iroquois', 'IL', true),('Jackson', 'IL', true),('Jasper', 'IL', true),
('Jefferson', 'IL', true),('Jersey', 'IL', true),('Jo Daviess', 'IL', true),('Johnson', 'IL', true),('Kane', 'IL', true),
('Kankakee', 'IL', true),('Kendall', 'IL', true),('Knox', 'IL', true),('Lake', 'IL', true),('LaSalle', 'IL', true),
('Lawrence', 'IL', true),('Lee', 'IL', true),('Livingston', 'IL', true),('Logan', 'IL', true),('Macon', 'IL', true),
('Macoupin', 'IL', true),('Madison', 'IL', true),('Marion', 'IL', true),('Marshall', 'IL', true),('Mason', 'IL', true),
('Massac', 'IL', true),('McDonough', 'IL', true),('McHenry', 'IL', true),('McLean', 'IL', true),('Menard', 'IL', true),
('Mercer', 'IL', true),('Monroe', 'IL', true),('Montgomery', 'IL', true),('Morgan', 'IL', true),('Moultrie', 'IL', true),
('Ogle', 'IL', true),('Peoria', 'IL', true),('Perry', 'IL', true),('Piatt', 'IL', true),('Pike', 'IL', true),
('Pope', 'IL', true),('Pulaski', 'IL', true),('Putnam', 'IL', true),('Randolph', 'IL', true),('Richland', 'IL', true),
('Rock Island', 'IL', true),('Saline', 'IL', true),('Sangamon', 'IL', true),('Schuyler', 'IL', true),('Scott', 'IL', true),
('Shelby', 'IL', true),('St. Clair', 'IL', true),('Stark', 'IL', true),('Stephenson', 'IL', true),('Tazewell', 'IL', true),
('Union', 'IL', true),('Vermilion', 'IL', true),('Wabash', 'IL', true),('Warren', 'IL', true),('Washington', 'IL', true),
('Wayne', 'IL', true),('White', 'IL', true),('Whiteside', 'IL', true),('Will', 'IL', true),('Williamson', 'IL', true),
('Winnebago', 'IL', true),('Woodford', 'IL', true),
-- Indiana (92 counties)
('Adams', 'IN', true),('Allen', 'IN', true),('Bartholomew', 'IN', true),('Benton', 'IN', true),('Blackford', 'IN', true),
('Boone', 'IN', true),('Brown', 'IN', true),('Carroll', 'IN', true),('Cass', 'IN', true),('Clark', 'IN', true),
('Clay', 'IN', true),('Clinton', 'IN', true),('Crawford', 'IN', true),('Daviess', 'IN', true),('Dearborn', 'IN', true),
('Decatur', 'IN', true),('DeKalb', 'IN', true),('Delaware', 'IN', true),('Dubois', 'IN', true),('Elkhart', 'IN', true),
('Fayette', 'IN', true),('Floyd', 'IN', true),('Fountain', 'IN', true),('Franklin', 'IN', true),('Fulton', 'IN', true),
('Gibson', 'IN', true),('Grant', 'IN', true),('Greene', 'IN', true),('Hamilton', 'IN', true),('Hancock', 'IN', true),
('Harrison', 'IN', true),('Hendricks', 'IN', true),('Henry', 'IN', true),('Howard', 'IN', true),('Huntington', 'IN', true),
('Jackson', 'IN', true),('Jasper', 'IN', true),('Jay', 'IN', true),('Jefferson', 'IN', true),('Jennings', 'IN', true),
('Johnson', 'IN', true),('Knox', 'IN', true),('Kosciusko', 'IN', true),('LaGrange', 'IN', true),('Lake', 'IN', true),
('LaPorte', 'IN', true),('Lawrence', 'IN', true),('Madison', 'IN', true),('Marion', 'IN', true),('Marshall', 'IN', true),
('Martin', 'IN', true),('Miami', 'IN', true),('Monroe', 'IN', true),('Montgomery', 'IN', true),('Morgan', 'IN', true),
('Newton', 'IN', true),('Noble', 'IN', true),('Ohio', 'IN', true),('Orange', 'IN', true),('Owen', 'IN', true),
('Parke', 'IN', true),('Perry', 'IN', true),('Pike', 'IN', true),('Porter', 'IN', true),('Posey', 'IN', true),
('Pulaski', 'IN', true),('Putnam', 'IN', true),('Randolph', 'IN', true),('Ripley', 'IN', true),('Rush', 'IN', true),
('Scott', 'IN', true),('Shelby', 'IN', true),('Spencer', 'IN', true),('St. Joseph', 'IN', true),('Starke', 'IN', true),
('Steuben', 'IN', true),('Sullivan', 'IN', true),('Switzerland', 'IN', true),('Tippecanoe', 'IN', true),('Tipton', 'IN', true),
('Union', 'IN', true),('Vanderburgh', 'IN', true),('Vermillion', 'IN', true),('Vigo', 'IN', true),('Wabash', 'IN', true),
('Warren', 'IN', true),('Warrick', 'IN', true),('Washington', 'IN', true),('Wayne', 'IN', true),('Wells', 'IN', true),
('White', 'IN', true),('Whitley', 'IN', true),
-- Iowa (99 counties)
('Adair', 'IA', true),('Adams', 'IA', true),('Allamakee', 'IA', true),('Appanoose', 'IA', true),('Audubon', 'IA', true),
('Benton', 'IA', true),('Black Hawk', 'IA', true),('Boone', 'IA', true),('Bremer', 'IA', true),('Buchanan', 'IA', true),
('Buena Vista', 'IA', true),('Butler', 'IA', true),('Calhoun', 'IA', true),('Carroll', 'IA', true),('Cass', 'IA', true),
('Cedar', 'IA', true),('Cerro Gordo', 'IA', true),('Cherokee', 'IA', true),('Chickasaw', 'IA', true),('Clarke', 'IA', true),
('Clay', 'IA', true),('Clayton', 'IA', true),('Clinton', 'IA', true),('Crawford', 'IA', true),('Dallas', 'IA', true),
('Davis', 'IA', true),('Decatur', 'IA', true),('Delaware', 'IA', true),('Des Moines', 'IA', true),('Dickinson', 'IA', true),
('Dubuque', 'IA', true),('Emmet', 'IA', true),('Fayette', 'IA', true),('Floyd', 'IA', true),('Franklin', 'IA', true),
('Fremont', 'IA', true),('Greene', 'IA', true),('Grundy', 'IA', true),('Guthrie', 'IA', true),('Hamilton', 'IA', true),
('Hancock', 'IA', true),('Hardin', 'IA', true),('Harrison', 'IA', true),('Henry', 'IA', true),('Howard', 'IA', true),
('Humboldt', 'IA', true),('Ida', 'IA', true),('Iowa', 'IA', true),('Jackson', 'IA', true),('Jasper', 'IA', true),
('Jefferson', 'IA', true),('Johnson', 'IA', true),('Jones', 'IA', true),('Keokuk', 'IA', true),('Kossuth', 'IA', true),
('Lee', 'IA', true),('Linn', 'IA', true),('Louisa', 'IA', true),('Lucas', 'IA', true),('Lyon', 'IA', true),
('Madison', 'IA', true),('Mahaska', 'IA', true),('Marion', 'IA', true),('Marshall', 'IA', true),('Mills', 'IA', true),
('Mitchell', 'IA', true),('Monona', 'IA', true),('Monroe', 'IA', true),('Montgomery', 'IA', true),('Muscatine', 'IA', true),
('O''Brien', 'IA', true),('Osceola', 'IA', true),('Page', 'IA', true),('Palo Alto', 'IA', true),('Plymouth', 'IA', true),
('Pocahontas', 'IA', true),('Polk', 'IA', true),('Pottawattamie', 'IA', true),('Poweshiek', 'IA', true),('Ringgold', 'IA', true),
('Sac', 'IA', true),('Scott', 'IA', true),('Shelby', 'IA', true),('Sioux', 'IA', true),('Story', 'IA', true),
('Tama', 'IA', true),('Taylor', 'IA', true),('Union', 'IA', true),('Van Buren', 'IA', true),('Wapello', 'IA', true),
('Warren', 'IA', true),('Washington', 'IA', true),('Wayne', 'IA', true),('Webster', 'IA', true),('Winnebago', 'IA', true),
('Winneshiek', 'IA', true),('Woodbury', 'IA', true),('Worth', 'IA', true),('Wright', 'IA', true),
-- Kansas (105 counties)
('Allen', 'KS', true),('Anderson', 'KS', true),('Atchison', 'KS', true),('Barber', 'KS', true),('Barton', 'KS', true),
('Bourbon', 'KS', true),('Brown', 'KS', true),('Butler', 'KS', true),('Chase', 'KS', true),('Chautauqua', 'KS', true),
('Cherokee', 'KS', true),('Cheyenne', 'KS', true),('Clark', 'KS', true),('Clay', 'KS', true),('Cloud', 'KS', true),
('Coffey', 'KS', true),('Comanche', 'KS', true),('Cowley', 'KS', true),('Crawford', 'KS', true),('Decatur', 'KS', true),
('Dickinson', 'KS', true),('Doniphan', 'KS', true),('Douglas', 'KS', true),('Edwards', 'KS', true),('Elk', 'KS', true),
('Ellis', 'KS', true),('Ellsworth', 'KS', true),('Finney', 'KS', true),('Ford', 'KS', true),('Franklin', 'KS', true),
('Geary', 'KS', true),('Gove', 'KS', true),('Graham', 'KS', true),('Grant', 'KS', true),('Gray', 'KS', true),
('Greeley', 'KS', true),('Greenwood', 'KS', true),('Hamilton', 'KS', true),('Harper', 'KS', true),('Harvey', 'KS', true),
('Haskell', 'KS', true),('Hodgeman', 'KS', true),('Jackson', 'KS', true),('Jefferson', 'KS', true),('Jewell', 'KS', true),
('Johnson', 'KS', true),('Kearny', 'KS', true),('Kingman', 'KS', true),('Kiowa', 'KS', true),('Labette', 'KS', true),
('Lane', 'KS', true),('Leavenworth', 'KS', true),('Lincoln', 'KS', true),('Linn', 'KS', true),('Logan', 'KS', true),
('Lyon', 'KS', true),('Marion', 'KS', true),('Marshall', 'KS', true),('McPherson', 'KS', true),('Meade', 'KS', true),
('Miami', 'KS', true),('Mitchell', 'KS', true),('Montgomery', 'KS', true),('Morris', 'KS', true),('Morton', 'KS', true),
('Nemaha', 'KS', true),('Neosho', 'KS', true),('Ness', 'KS', true),('Norton', 'KS', true),('Osage', 'KS', true),
('Osborne', 'KS', true),('Ottawa', 'KS', true),('Pawnee', 'KS', true),('Phillips', 'KS', true),('Pottawatomie', 'KS', true),
('Pratt', 'KS', true),('Rawlins', 'KS', true),('Reno', 'KS', true),('Republic', 'KS', true),('Rice', 'KS', true),
('Riley', 'KS', true),('Rooks', 'KS', true),('Rush', 'KS', true),('Russell', 'KS', true),('Saline', 'KS', true),
('Scott', 'KS', true),('Sedgwick', 'KS', true),('Seward', 'KS', true),('Shawnee', 'KS', true),('Sheridan', 'KS', true),
('Sherman', 'KS', true),('Smith', 'KS', true),('Stafford', 'KS', true),('Stanton', 'KS', true),('Stevens', 'KS', true),
('Sumner', 'KS', true),('Thomas', 'KS', true),('Trego', 'KS', true),('Wabaunsee', 'KS', true),('Wallace', 'KS', true),
('Washington', 'KS', true),('Wichita', 'KS', true),('Wilson', 'KS', true),('Woodson', 'KS', true),('Wyandotte', 'KS', true),
-- Louisiana (64 parishes)
('Acadia', 'LA', true),('Allen', 'LA', true),('Ascension', 'LA', true),('Assumption', 'LA', true),('Avoyelles', 'LA', true),
('Beauregard', 'LA', true),('Bienville', 'LA', true),('Bossier', 'LA', true),('Caddo', 'LA', true),('Calcasieu', 'LA', true),
('Caldwell', 'LA', true),('Cameron', 'LA', true),('Catahoula', 'LA', true),('Claiborne', 'LA', true),('Concordia', 'LA', true),
('De Soto', 'LA', true),('East Baton Rouge', 'LA', true),('East Carroll', 'LA', true),('East Feliciana', 'LA', true),('Evangeline', 'LA', true),
('Franklin', 'LA', true),('Grant', 'LA', true),('Iberia', 'LA', true),('Iberville', 'LA', true),('Jackson', 'LA', true),
('Jefferson', 'LA', true),('Jefferson Davis', 'LA', true),('La Salle', 'LA', true),('Lafayette', 'LA', true),('Lafourche', 'LA', true),
('Lincoln', 'LA', true),('Livingston', 'LA', true),('Madison', 'LA', true),('Morehouse', 'LA', true),('Natchitoches', 'LA', true),
('Orleans', 'LA', true),('Ouachita', 'LA', true),('Plaquemines', 'LA', true),('Pointe Coupee', 'LA', true),('Rapides', 'LA', true),
('Red River', 'LA', true),('Richland', 'LA', true),('Sabine', 'LA', true),('St. Bernard', 'LA', true),('St. Charles', 'LA', true),
('St. Helena', 'LA', true),('St. James', 'LA', true),('St. John the Baptist', 'LA', true),('St. Landry', 'LA', true),('St. Martin', 'LA', true),
('St. Mary', 'LA', true),('St. Tammany', 'LA', true),('Tangipahoa', 'LA', true),('Tensas', 'LA', true),('Terrebonne', 'LA', true),
('Union', 'LA', true),('Vermilion', 'LA', true),('Vernon', 'LA', true),('Washington', 'LA', true),('Webster', 'LA', true),
('West Baton Rouge', 'LA', true),('West Carroll', 'LA', true),('West Feliciana', 'LA', true),('Winn', 'LA', true),
-- Maine (16 counties)
('Androscoggin', 'ME', true),('Aroostook', 'ME', true),('Cumberland', 'ME', true),('Franklin', 'ME', true),
('Hancock', 'ME', true),('Kennebec', 'ME', true),('Knox', 'ME', true),('Lincoln', 'ME', true),
('Oxford', 'ME', true),('Penobscot', 'ME', true),('Piscataquis', 'ME', true),('Sagadahoc', 'ME', true),
('Somerset', 'ME', true),('Waldo', 'ME', true),('Washington', 'ME', true),('York', 'ME', true),
-- Maryland (24 counties)
('Allegany', 'MD', true),('Anne Arundel', 'MD', true),('Baltimore', 'MD', true),('Baltimore City', 'MD', true),
('Calvert', 'MD', true),('Caroline', 'MD', true),('Carroll', 'MD', true),('Cecil', 'MD', true),
('Charles', 'MD', true),('Dorchester', 'MD', true),('Frederick', 'MD', true),('Garrett', 'MD', true),
('Harford', 'MD', true),('Howard', 'MD', true),('Kent', 'MD', true),('Montgomery', 'MD', true),
('Prince George''s', 'MD', true),('Queen Anne''s', 'MD', true),('Somerset', 'MD', true),('St. Mary''s', 'MD', true),
('Talbot', 'MD', true),('Washington', 'MD', true),('Wicomico', 'MD', true),('Worcester', 'MD', true),
-- Massachusetts (14 counties)
('Barnstable', 'MA', true),('Berkshire', 'MA', true),('Bristol', 'MA', true),('Dukes', 'MA', true),
('Essex', 'MA', true),('Franklin', 'MA', true),('Hampden', 'MA', true),('Hampshire', 'MA', true),
('Middlesex', 'MA', true),('Nantucket', 'MA', true),('Norfolk', 'MA', true),('Plymouth', 'MA', true),
('Suffolk', 'MA', true),('Worcester', 'MA', true)
ON CONFLICT DO NOTHING;
