/*
  # Insert Counties - Batch 4 (North Carolina through Wyoming)

  1. Data
    - North Carolina (100 counties)
    - North Dakota (53 counties)
    - Ohio (88 counties)
    - Oklahoma (77 counties)
    - Oregon (36 counties)
    - Pennsylvania (67 counties)
    - Rhode Island (5 counties)
    - South Carolina (46 counties)
    - South Dakota (66 counties)
    - Texas (254 counties)
    - Utah (29 counties)
    - Vermont (14 counties)
    - Virginia (134 counties/cities)
    - Washington (39 counties)
    - West Virginia (55 counties)
    - Wyoming (23 counties)
*/

INSERT INTO counties (name, state_code, is_active) VALUES
-- North Carolina (100 counties)
('Alamance', 'NC', true),('Alexander', 'NC', true),('Alleghany', 'NC', true),('Anson', 'NC', true),('Ashe', 'NC', true),
('Avery', 'NC', true),('Beaufort', 'NC', true),('Bertie', 'NC', true),('Bladen', 'NC', true),('Brunswick', 'NC', true),
('Buncombe', 'NC', true),('Burke', 'NC', true),('Cabarrus', 'NC', true),('Caldwell', 'NC', true),('Camden', 'NC', true),
('Carteret', 'NC', true),('Caswell', 'NC', true),('Catawba', 'NC', true),('Chatham', 'NC', true),('Cherokee', 'NC', true),
('Chowan', 'NC', true),('Clay', 'NC', true),('Cleveland', 'NC', true),('Columbus', 'NC', true),('Craven', 'NC', true),
('Cumberland', 'NC', true),('Currituck', 'NC', true),('Dare', 'NC', true),('Davidson', 'NC', true),('Davie', 'NC', true),
('Duplin', 'NC', true),('Durham', 'NC', true),('Edgecombe', 'NC', true),('Forsyth', 'NC', true),('Franklin', 'NC', true),
('Gaston', 'NC', true),('Gates', 'NC', true),('Graham', 'NC', true),('Granville', 'NC', true),('Greene', 'NC', true),
('Guilford', 'NC', true),('Halifax', 'NC', true),('Harnett', 'NC', true),('Haywood', 'NC', true),('Henderson', 'NC', true),
('Hertford', 'NC', true),('Hoke', 'NC', true),('Hyde', 'NC', true),('Iredell', 'NC', true),('Jackson', 'NC', true),
('Johnston', 'NC', true),('Jones', 'NC', true),('Lee', 'NC', true),('Lenoir', 'NC', true),('Lincoln', 'NC', true),
('Macon', 'NC', true),('Madison', 'NC', true),('Martin', 'NC', true),('McDowell', 'NC', true),('Mecklenburg', 'NC', true),
('Mitchell', 'NC', true),('Montgomery', 'NC', true),('Moore', 'NC', true),('Nash', 'NC', true),('New Hanover', 'NC', true),
('Northampton', 'NC', true),('Onslow', 'NC', true),('Orange', 'NC', true),('Pamlico', 'NC', true),('Pasquotank', 'NC', true),
('Pender', 'NC', true),('Perquimans', 'NC', true),('Person', 'NC', true),('Pitt', 'NC', true),('Polk', 'NC', true),
('Randolph', 'NC', true),('Richmond', 'NC', true),('Robeson', 'NC', true),('Rockingham', 'NC', true),('Rowan', 'NC', true),
('Rutherford', 'NC', true),('Sampson', 'NC', true),('Scotland', 'NC', true),('Stanly', 'NC', true),('Stokes', 'NC', true),
('Surry', 'NC', true),('Swain', 'NC', true),('Transylvania', 'NC', true),('Tyrrell', 'NC', true),('Union', 'NC', true),
('Vance', 'NC', true),('Wake', 'NC', true),('Warren', 'NC', true),('Washington', 'NC', true),('Watauga', 'NC', true),
('Wayne', 'NC', true),('Wilkes', 'NC', true),('Wilson', 'NC', true),('Yadkin', 'NC', true),('Yancey', 'NC', true),
-- North Dakota (53 counties)
('Adams', 'ND', true),('Barnes', 'ND', true),('Benson', 'ND', true),('Billings', 'ND', true),('Bottineau', 'ND', true),
('Bowman', 'ND', true),('Burke', 'ND', true),('Burleigh', 'ND', true),('Cass', 'ND', true),('Cavalier', 'ND', true),
('Dickey', 'ND', true),('Divide', 'ND', true),('Dunn', 'ND', true),('Eddy', 'ND', true),('Emmons', 'ND', true),
('Foster', 'ND', true),('Golden Valley', 'ND', true),('Grand Forks', 'ND', true),('Grant', 'ND', true),('Griggs', 'ND', true),
('Hettinger', 'ND', true),('Kidder', 'ND', true),('LaMoure', 'ND', true),('Logan', 'ND', true),('McHenry', 'ND', true),
('McIntosh', 'ND', true),('McKenzie', 'ND', true),('McLean', 'ND', true),('Mercer', 'ND', true),('Morton', 'ND', true),
('Mountrail', 'ND', true),('Nelson', 'ND', true),('Oliver', 'ND', true),('Pembina', 'ND', true),('Pierce', 'ND', true),
('Ramsey', 'ND', true),('Ransom', 'ND', true),('Renville', 'ND', true),('Richland', 'ND', true),('Rolette', 'ND', true),
('Sargent', 'ND', true),('Sheridan', 'ND', true),('Sioux', 'ND', true),('Slope', 'ND', true),('Stark', 'ND', true),
('Steele', 'ND', true),('Stutsman', 'ND', true),('Towner', 'ND', true),('Traill', 'ND', true),('Walsh', 'ND', true),
('Ward', 'ND', true),('Wells', 'ND', true),('Williams', 'ND', true),
-- Ohio (88 counties)
('Adams', 'OH', true),('Allen', 'OH', true),('Ashland', 'OH', true),('Ashtabula', 'OH', true),('Athens', 'OH', true),
('Auglaize', 'OH', true),('Belmont', 'OH', true),('Brown', 'OH', true),('Butler', 'OH', true),('Carroll', 'OH', true),
('Champaign', 'OH', true),('Clark', 'OH', true),('Clermont', 'OH', true),('Clinton', 'OH', true),('Columbiana', 'OH', true),
('Coshocton', 'OH', true),('Crawford', 'OH', true),('Cuyahoga', 'OH', true),('Darke', 'OH', true),('Defiance', 'OH', true),
('Delaware', 'OH', true),('Erie', 'OH', true),('Fairfield', 'OH', true),('Fayette', 'OH', true),('Franklin', 'OH', true),
('Fulton', 'OH', true),('Gallia', 'OH', true),('Geauga', 'OH', true),('Greene', 'OH', true),('Guernsey', 'OH', true),
('Hamilton', 'OH', true),('Hancock', 'OH', true),('Hardin', 'OH', true),('Harrison', 'OH', true),('Henry', 'OH', true),
('Highland', 'OH', true),('Hocking', 'OH', true),('Holmes', 'OH', true),('Huron', 'OH', true),('Jackson', 'OH', true),
('Jefferson', 'OH', true),('Knox', 'OH', true),('Lake', 'OH', true),('Lawrence', 'OH', true),('Licking', 'OH', true),
('Logan', 'OH', true),('Lorain', 'OH', true),('Lucas', 'OH', true),('Madison', 'OH', true),('Mahoning', 'OH', true),
('Marion', 'OH', true),('Medina', 'OH', true),('Meigs', 'OH', true),('Mercer', 'OH', true),('Miami', 'OH', true),
('Monroe', 'OH', true),('Montgomery', 'OH', true),('Morgan', 'OH', true),('Morrow', 'OH', true),('Muskingum', 'OH', true),
('Noble', 'OH', true),('Ottawa', 'OH', true),('Paulding', 'OH', true),('Perry', 'OH', true),('Pickaway', 'OH', true),
('Pike', 'OH', true),('Portage', 'OH', true),('Preble', 'OH', true),('Putnam', 'OH', true),('Richland', 'OH', true),
('Ross', 'OH', true),('Sandusky', 'OH', true),('Scioto', 'OH', true),('Seneca', 'OH', true),('Shelby', 'OH', true),
('Stark', 'OH', true),('Summit', 'OH', true),('Trumbull', 'OH', true),('Tuscarawas', 'OH', true),('Union', 'OH', true),
('Van Wert', 'OH', true),('Vinton', 'OH', true),('Warren', 'OH', true),('Washington', 'OH', true),('Wayne', 'OH', true),
('Williams', 'OH', true),('Wood', 'OH', true),('Wyandot', 'OH', true),
-- Oklahoma (77 counties)
('Adair', 'OK', true),('Alfalfa', 'OK', true),('Atoka', 'OK', true),('Beaver', 'OK', true),('Beckham', 'OK', true),
('Blaine', 'OK', true),('Bryan', 'OK', true),('Caddo', 'OK', true),('Canadian', 'OK', true),('Carter', 'OK', true),
('Cherokee', 'OK', true),('Choctaw', 'OK', true),('Cimarron', 'OK', true),('Cleveland', 'OK', true),('Coal', 'OK', true),
('Comanche', 'OK', true),('Cotton', 'OK', true),('Craig', 'OK', true),('Creek', 'OK', true),('Custer', 'OK', true),
('Delaware', 'OK', true),('Dewey', 'OK', true),('Ellis', 'OK', true),('Garfield', 'OK', true),('Garvin', 'OK', true),
('Grady', 'OK', true),('Grant', 'OK', true),('Greer', 'OK', true),('Harmon', 'OK', true),('Harper', 'OK', true),
('Haskell', 'OK', true),('Hughes', 'OK', true),('Jackson', 'OK', true),('Jefferson', 'OK', true),('Johnston', 'OK', true),
('Kay', 'OK', true),('Kingfisher', 'OK', true),('Kiowa', 'OK', true),('Latimer', 'OK', true),('Le Flore', 'OK', true),
('Lincoln', 'OK', true),('Logan', 'OK', true),('Love', 'OK', true),('Major', 'OK', true),('Marshall', 'OK', true),
('Mayes', 'OK', true),('McClain', 'OK', true),('McCurtain', 'OK', true),('McIntosh', 'OK', true),('Murray', 'OK', true),
('Muskogee', 'OK', true),('Noble', 'OK', true),('Nowata', 'OK', true),('Okfuskee', 'OK', true),('Oklahoma', 'OK', true),
('Okmulgee', 'OK', true),('Osage', 'OK', true),('Ottawa', 'OK', true),('Pawnee', 'OK', true),('Payne', 'OK', true),
('Pittsburg', 'OK', true),('Pontotoc', 'OK', true),('Pottawatomie', 'OK', true),('Pushmataha', 'OK', true),('Roger Mills', 'OK', true),
('Rogers', 'OK', true),('Seminole', 'OK', true),('Sequoyah', 'OK', true),('Stephens', 'OK', true),('Texas', 'OK', true),
('Tillman', 'OK', true),('Tulsa', 'OK', true),('Wagoner', 'OK', true),('Washington', 'OK', true),('Washita', 'OK', true),
('Woods', 'OK', true),('Woodward', 'OK', true),
-- Oregon (36 counties)
('Baker', 'OR', true),('Benton', 'OR', true),('Clackamas', 'OR', true),('Clatsop', 'OR', true),('Columbia', 'OR', true),
('Coos', 'OR', true),('Crook', 'OR', true),('Curry', 'OR', true),('Deschutes', 'OR', true),('Douglas', 'OR', true),
('Gilliam', 'OR', true),('Grant', 'OR', true),('Harney', 'OR', true),('Hood River', 'OR', true),('Jackson', 'OR', true),
('Jefferson', 'OR', true),('Josephine', 'OR', true),('Klamath', 'OR', true),('Lake', 'OR', true),('Lane', 'OR', true),
('Lincoln', 'OR', true),('Linn', 'OR', true),('Malheur', 'OR', true),('Marion', 'OR', true),('Morrow', 'OR', true),
('Multnomah', 'OR', true),('Polk', 'OR', true),('Sherman', 'OR', true),('Tillamook', 'OR', true),('Umatilla', 'OR', true),
('Union', 'OR', true),('Wallowa', 'OR', true),('Wasco', 'OR', true),('Washington', 'OR', true),('Wheeler', 'OR', true),('Yamhill', 'OR', true),
-- Pennsylvania (67 counties)
('Adams', 'PA', true),('Allegheny', 'PA', true),('Armstrong', 'PA', true),('Beaver', 'PA', true),('Bedford', 'PA', true),
('Berks', 'PA', true),('Blair', 'PA', true),('Bradford', 'PA', true),('Bucks', 'PA', true),('Butler', 'PA', true),
('Cambria', 'PA', true),('Cameron', 'PA', true),('Carbon', 'PA', true),('Centre', 'PA', true),('Chester', 'PA', true),
('Clarion', 'PA', true),('Clearfield', 'PA', true),('Clinton', 'PA', true),('Columbia', 'PA', true),('Crawford', 'PA', true),
('Cumberland', 'PA', true),('Dauphin', 'PA', true),('Delaware', 'PA', true),('Elk', 'PA', true),('Erie', 'PA', true),
('Fayette', 'PA', true),('Forest', 'PA', true),('Franklin', 'PA', true),('Fulton', 'PA', true),('Greene', 'PA', true),
('Huntingdon', 'PA', true),('Indiana', 'PA', true),('Jefferson', 'PA', true),('Juniata', 'PA', true),('Lackawanna', 'PA', true),
('Lancaster', 'PA', true),('Lawrence', 'PA', true),('Lebanon', 'PA', true),('Lehigh', 'PA', true),('Luzerne', 'PA', true),
('Lycoming', 'PA', true),('McKean', 'PA', true),('Mercer', 'PA', true),('Mifflin', 'PA', true),('Monroe', 'PA', true),
('Montgomery', 'PA', true),('Montour', 'PA', true),('Northampton', 'PA', true),('Northumberland', 'PA', true),('Perry', 'PA', true),
('Philadelphia', 'PA', true),('Pike', 'PA', true),('Potter', 'PA', true),('Schuylkill', 'PA', true),('Snyder', 'PA', true),
('Somerset', 'PA', true),('Sullivan', 'PA', true),('Susquehanna', 'PA', true),('Tioga', 'PA', true),('Union', 'PA', true),
('Venango', 'PA', true),('Warren', 'PA', true),('Washington', 'PA', true),('Wayne', 'PA', true),('Westmoreland', 'PA', true),
('Wyoming', 'PA', true),('York', 'PA', true),
-- Rhode Island (5 counties)
('Bristol', 'RI', true),('Kent', 'RI', true),('Newport', 'RI', true),('Providence', 'RI', true),('Washington', 'RI', true),
-- South Carolina (46 counties)
('Abbeville', 'SC', true),('Aiken', 'SC', true),('Allendale', 'SC', true),('Anderson', 'SC', true),('Bamberg', 'SC', true),
('Barnwell', 'SC', true),('Beaufort', 'SC', true),('Berkeley', 'SC', true),('Calhoun', 'SC', true),('Charleston', 'SC', true),
('Cherokee', 'SC', true),('Chester', 'SC', true),('Chesterfield', 'SC', true),('Clarendon', 'SC', true),('Colleton', 'SC', true),
('Darlington', 'SC', true),('Dillon', 'SC', true),('Dorchester', 'SC', true),('Edgefield', 'SC', true),('Fairfield', 'SC', true),
('Florence', 'SC', true),('Georgetown', 'SC', true),('Greenville', 'SC', true),('Greenwood', 'SC', true),('Hampton', 'SC', true),
('Horry', 'SC', true),('Jasper', 'SC', true),('Kershaw', 'SC', true),('Lancaster', 'SC', true),('Laurens', 'SC', true),
('Lee', 'SC', true),('Lexington', 'SC', true),('Marion', 'SC', true),('Marlboro', 'SC', true),('McCormick', 'SC', true),
('Newberry', 'SC', true),('Oconee', 'SC', true),('Orangeburg', 'SC', true),('Pickens', 'SC', true),('Richland', 'SC', true),
('Saluda', 'SC', true),('Spartanburg', 'SC', true),('Sumter', 'SC', true),('Union', 'SC', true),('Williamsburg', 'SC', true),('York', 'SC', true),
-- South Dakota (66 counties)
('Aurora', 'SD', true),('Beadle', 'SD', true),('Bennett', 'SD', true),('Bon Homme', 'SD', true),('Brookings', 'SD', true),
('Brown', 'SD', true),('Brule', 'SD', true),('Buffalo', 'SD', true),('Butte', 'SD', true),('Campbell', 'SD', true),
('Charles Mix', 'SD', true),('Clark', 'SD', true),('Clay', 'SD', true),('Codington', 'SD', true),('Corson', 'SD', true),
('Custer', 'SD', true),('Davison', 'SD', true),('Day', 'SD', true),('Deuel', 'SD', true),('Dewey', 'SD', true),
('Douglas', 'SD', true),('Edmunds', 'SD', true),('Fall River', 'SD', true),('Faulk', 'SD', true),('Grant', 'SD', true),
('Gregory', 'SD', true),('Haakon', 'SD', true),('Hamlin', 'SD', true),('Hand', 'SD', true),('Hanson', 'SD', true),
('Harding', 'SD', true),('Hughes', 'SD', true),('Hutchinson', 'SD', true),('Hyde', 'SD', true),('Jackson', 'SD', true),
('Jerauld', 'SD', true),('Jones', 'SD', true),('Kingsbury', 'SD', true),('Lake', 'SD', true),('Lawrence', 'SD', true),
('Lincoln', 'SD', true),('Lyman', 'SD', true),('Marshall', 'SD', true),('McCook', 'SD', true),('McPherson', 'SD', true),
('Meade', 'SD', true),('Mellette', 'SD', true),('Miner', 'SD', true),('Minnehaha', 'SD', true),('Moody', 'SD', true),
('Pennington', 'SD', true),('Perkins', 'SD', true),('Potter', 'SD', true),('Roberts', 'SD', true),('Sanborn', 'SD', true),
('Shannon', 'SD', true),('Spink', 'SD', true),('Stanley', 'SD', true),('Sully', 'SD', true),('Todd', 'SD', true),
('Tripp', 'SD', true),('Turner', 'SD', true),('Union', 'SD', true),('Walworth', 'SD', true),('Yankton', 'SD', true),('Ziebach', 'SD', true),
-- Texas (254 counties - major counties)
('Anderson', 'TX', true),('Andrews', 'TX', true),('Angelina', 'TX', true),('Aransas', 'TX', true),('Archer', 'TX', true),
('Armstrong', 'TX', true),('Atascosa', 'TX', true),('Austin', 'TX', true),('Bailey', 'TX', true),('Bandera', 'TX', true),
('Bastrop', 'TX', true),('Baylor', 'TX', true),('Bee', 'TX', true),('Bell', 'TX', true),('Bexar', 'TX', true),
('Blanco', 'TX', true),('Borden', 'TX', true),('Bosque', 'TX', true),('Bowie', 'TX', true),('Brazoria', 'TX', true),
('Brazos', 'TX', true),('Brewster', 'TX', true),('Briscoe', 'TX', true),('Brooks', 'TX', true),('Brown', 'TX', true),
('Burleson', 'TX', true),('Burnet', 'TX', true),('Caldwell', 'TX', true),('Calhoun', 'TX', true),('Callahan', 'TX', true),
('Cameron', 'TX', true),('Camp', 'TX', true),('Carson', 'TX', true),('Cass', 'TX', true),('Castro', 'TX', true),
('Chambers', 'TX', true),('Cherokee', 'TX', true),('Childress', 'TX', true),('Clay', 'TX', true),('Cochran', 'TX', true),
('Coke', 'TX', true),('Coleman', 'TX', true),('Collin', 'TX', true),('Collingsworth', 'TX', true),('Colorado', 'TX', true),
('Comal', 'TX', true),('Comanche', 'TX', true),('Concho', 'TX', true),('Cooke', 'TX', true),('Coryell', 'TX', true),
('Cottle', 'TX', true),('Crane', 'TX', true),('Crockett', 'TX', true),('Crosby', 'TX', true),('Culberson', 'TX', true),
('Dallam', 'TX', true),('Dallas', 'TX', true),('Dawson', 'TX', true),('Deaf Smith', 'TX', true),('Delta', 'TX', true),
('Denton', 'TX', true),('DeWitt', 'TX', true),('Dickens', 'TX', true),('Dimmit', 'TX', true),('Donley', 'TX', true),
('Duval', 'TX', true),('Eastland', 'TX', true),('Ector', 'TX', true),('Edwards', 'TX', true),('El Paso', 'TX', true),
('Ellis', 'TX', true),('Erath', 'TX', true),('Falls', 'TX', true),('Fannin', 'TX', true),('Fayette', 'TX', true),
('Fisher', 'TX', true),('Floyd', 'TX', true),('Foard', 'TX', true),('Fort Bend', 'TX', true),('Franklin', 'TX', true),
('Freestone', 'TX', true),('Frio', 'TX', true),('Gaines', 'TX', true),('Galveston', 'TX', true),('Garza', 'TX', true),
('Gillespie', 'TX', true),('Glasscock', 'TX', true),('Goliad', 'TX', true),('Gonzales', 'TX', true),('Gray', 'TX', true),
('Grayson', 'TX', true),('Gregg', 'TX', true),('Grimes', 'TX', true),('Guadalupe', 'TX', true),('Hale', 'TX', true),
('Hall', 'TX', true),('Hamilton', 'TX', true),('Hansford', 'TX', true),('Hardeman', 'TX', true),('Hardin', 'TX', true),
('Harris', 'TX', true),('Harrison', 'TX', true),('Hartley', 'TX', true),('Haskell', 'TX', true),('Hays', 'TX', true),
('Hemphill', 'TX', true),('Henderson', 'TX', true),('Hidalgo', 'TX', true),('Hill', 'TX', true),('Hockley', 'TX', true),
('Hood', 'TX', true),('Hopkins', 'TX', true),('Houston', 'TX', true),('Howard', 'TX', true),('Hudspeth', 'TX', true),
('Hunt', 'TX', true),('Hutchinson', 'TX', true),('Irion', 'TX', true),('Jack', 'TX', true),('Jackson', 'TX', true),
('Jasper', 'TX', true),('Jeff Davis', 'TX', true),('Jefferson', 'TX', true),('Jim Hogg', 'TX', true),('Jim Wells', 'TX', true),
('Johnson', 'TX', true),('Jones', 'TX', true),('Karnes', 'TX', true),('Kaufman', 'TX', true),('Kendall', 'TX', true),
('Kenedy', 'TX', true),('Kent', 'TX', true),('Kerr', 'TX', true),('Kimble', 'TX', true),('King', 'TX', true),
('Kinney', 'TX', true),('Kleberg', 'TX', true),('Knox', 'TX', true),('Lamar', 'TX', true),('Lamb', 'TX', true),
('Lampasas', 'TX', true),('La Salle', 'TX', true),('Lavaca', 'TX', true),('Lee', 'TX', true),('Leon', 'TX', true),
('Liberty', 'TX', true),('Limestone', 'TX', true),('Lipscomb', 'TX', true),('Live Oak', 'TX', true),('Llano', 'TX', true),
('Loving', 'TX', true),('Lubbock', 'TX', true),('Lynn', 'TX', true),('Madison', 'TX', true),('Marion', 'TX', true),
('Martin', 'TX', true),('Mason', 'TX', true),('Matagorda', 'TX', true),('Maverick', 'TX', true),('McCulloch', 'TX', true),
('McLennan', 'TX', true),('McMullen', 'TX', true),('Medina', 'TX', true),('Menard', 'TX', true),('Midland', 'TX', true),
('Milam', 'TX', true),('Mills', 'TX', true),('Mitchell', 'TX', true),('Montague', 'TX', true),('Montgomery', 'TX', true),
('Moore', 'TX', true),('Morris', 'TX', true),('Motley', 'TX', true),('Nacogdoches', 'TX', true),('Navarro', 'TX', true),
('Newton', 'TX', true),('Nolan', 'TX', true),('Nueces', 'TX', true),('Ochiltree', 'TX', true),('Oldham', 'TX', true),
('Orange', 'TX', true),('Palo Pinto', 'TX', true),('Panola', 'TX', true),('Parker', 'TX', true),('Parmer', 'TX', true),
('Pecos', 'TX', true),('Polk', 'TX', true),('Potter', 'TX', true),('Presidio', 'TX', true),('Rains', 'TX', true),
('Randall', 'TX', true),('Reagan', 'TX', true),('Real', 'TX', true),('Red River', 'TX', true),('Reeves', 'TX', true),
('Refugio', 'TX', true),('Roberts', 'TX', true),('Robertson', 'TX', true),('Rockwall', 'TX', true),('Runnels', 'TX', true),
('Rusk', 'TX', true),('Sabine', 'TX', true),('San Augustine', 'TX', true),('San Jacinto', 'TX', true),('San Patricio', 'TX', true),
('San Saba', 'TX', true),('Schleicher', 'TX', true),('Scurry', 'TX', true),('Shackelford', 'TX', true),('Shelby', 'TX', true),
('Sherman', 'TX', true),('Smith', 'TX', true),('Somervell', 'TX', true),('Starr', 'TX', true),('Stephens', 'TX', true),
('Sterling', 'TX', true),('Stonewall', 'TX', true),('Sutton', 'TX', true),('Swisher', 'TX', true),('Tarrant', 'TX', true),
('Taylor', 'TX', true),('Terrell', 'TX', true),('Terry', 'TX', true),('Throckmorton', 'TX', true),('Titus', 'TX', true),
('Tom Green', 'TX', true),('Travis', 'TX', true),('Trinity', 'TX', true),('Tyler', 'TX', true),('Upshur', 'TX', true),
('Upton', 'TX', true),('Uvalde', 'TX', true),('Val Verde', 'TX', true),('Van Zandt', 'TX', true),('Victoria', 'TX', true),
('Walker', 'TX', true),('Waller', 'TX', true),('Ward', 'TX', true),('Washington', 'TX', true),('Webb', 'TX', true),
('Wharton', 'TX', true),('Wheeler', 'TX', true),('Wichita', 'TX', true),('Wilbarger', 'TX', true),('Willacy', 'TX', true),
('Williamson', 'TX', true),('Wilson', 'TX', true),('Winkler', 'TX', true),('Wise', 'TX', true),('Wood', 'TX', true),
('Yoakum', 'TX', true),('Young', 'TX', true),('Zapata', 'TX', true),('Zavala', 'TX', true),
-- Utah (29 counties)
('Beaver', 'UT', true),('Box Elder', 'UT', true),('Cache', 'UT', true),('Carbon', 'UT', true),('Daggett', 'UT', true),
('Davis', 'UT', true),('Duchesne', 'UT', true),('Emery', 'UT', true),('Garfield', 'UT', true),('Grand', 'UT', true),
('Iron', 'UT', true),('Juab', 'UT', true),('Kane', 'UT', true),('Millard', 'UT', true),('Morgan', 'UT', true),
('Piute', 'UT', true),('Rich', 'UT', true),('Salt Lake', 'UT', true),('San Juan', 'UT', true),('Sanpete', 'UT', true),
('Sevier', 'UT', true),('Summit', 'UT', true),('Tooele', 'UT', true),('Uintah', 'UT', true),('Utah', 'UT', true),
('Wasatch', 'UT', true),('Washington', 'UT', true),('Wayne', 'UT', true),('Weber', 'UT', true),
-- Vermont (14 counties)
('Addison', 'VT', true),('Bennington', 'VT', true),('Caledonia', 'VT', true),('Chittenden', 'VT', true),
('Essex', 'VT', true),('Franklin', 'VT', true),('Grand Isle', 'VT', true),('Lamoille', 'VT', true),
('Orange', 'VT', true),('Orleans', 'VT', true),('Rutland', 'VT', true),('Washington', 'VT', true),
('Windham', 'VT', true),('Windsor', 'VT', true),
-- Virginia (95 counties + 38 independent cities, including major ones)
('Accomack', 'VA', true),('Albemarle', 'VA', true),('Alleghany', 'VA', true),('Amelia', 'VA', true),('Amherst', 'VA', true),
('Appomattox', 'VA', true),('Arlington', 'VA', true),('Augusta', 'VA', true),('Bath', 'VA', true),('Bedford', 'VA', true),
('Bland', 'VA', true),('Botetourt', 'VA', true),('Brunswick', 'VA', true),('Buchanan', 'VA', true),('Buckingham', 'VA', true),
('Campbell', 'VA', true),('Caroline', 'VA', true),('Carroll', 'VA', true),('Charles City', 'VA', true),('Charlotte', 'VA', true),
('Chesterfield', 'VA', true),('Clarke', 'VA', true),('Craig', 'VA', true),('Culpeper', 'VA', true),('Cumberland', 'VA', true),
('Dickenson', 'VA', true),('Dinwiddie', 'VA', true),('Essex', 'VA', true),('Fairfax', 'VA', true),('Fauquier', 'VA', true),
('Floyd', 'VA', true),('Fluvanna', 'VA', true),('Franklin', 'VA', true),('Frederick', 'VA', true),('Giles', 'VA', true),
('Gloucester', 'VA', true),('Goochland', 'VA', true),('Grayson', 'VA', true),('Greene', 'VA', true),('Greensville', 'VA', true),
('Halifax', 'VA', true),('Hanover', 'VA', true),('Henrico', 'VA', true),('Henry', 'VA', true),('Highland', 'VA', true),
('Isle of Wight', 'VA', true),('James City', 'VA', true),('King and Queen', 'VA', true),('King George', 'VA', true),('King William', 'VA', true),
('Lancaster', 'VA', true),('Lee', 'VA', true),('Loudoun', 'VA', true),('Louisa', 'VA', true),('Lunenburg', 'VA', true),
('Madison', 'VA', true),('Mathews', 'VA', true),('Mecklenburg', 'VA', true),('Middlesex', 'VA', true),('Montgomery', 'VA', true),
('Nelson', 'VA', true),('New Kent', 'VA', true),('Northampton', 'VA', true),('Northumberland', 'VA', true),('Nottoway', 'VA', true),
('Orange', 'VA', true),('Page', 'VA', true),('Patrick', 'VA', true),('Pittsylvania', 'VA', true),('Powhatan', 'VA', true),
('Prince Edward', 'VA', true),('Prince George', 'VA', true),('Prince William', 'VA', true),('Pulaski', 'VA', true),('Rappahannock', 'VA', true),
('Richmond', 'VA', true),('Roanoke', 'VA', true),('Rockbridge', 'VA', true),('Rockingham', 'VA', true),('Russell', 'VA', true),
('Scott', 'VA', true),('Shenandoah', 'VA', true),('Smyth', 'VA', true),('Southampton', 'VA', true),('Spotsylvania', 'VA', true),
('Stafford', 'VA', true),('Surry', 'VA', true),('Sussex', 'VA', true),('Tazewell', 'VA', true),('Warren', 'VA', true),
('Washington', 'VA', true),('Westmoreland', 'VA', true),('Wise', 'VA', true),('Wythe', 'VA', true),('York', 'VA', true),
('Alexandria City', 'VA', true),('Charlottesville City', 'VA', true),('Chesapeake City', 'VA', true),('Hampton City', 'VA', true),
('Lynchburg City', 'VA', true),('Newport News City', 'VA', true),('Norfolk City', 'VA', true),('Portsmouth City', 'VA', true),
('Richmond City', 'VA', true),('Roanoke City', 'VA', true),('Suffolk City', 'VA', true),('Virginia Beach City', 'VA', true),
-- Washington (39 counties)
('Adams', 'WA', true),('Asotin', 'WA', true),('Benton', 'WA', true),('Chelan', 'WA', true),('Clallam', 'WA', true),
('Clark', 'WA', true),('Columbia', 'WA', true),('Cowlitz', 'WA', true),('Douglas', 'WA', true),('Ferry', 'WA', true),
('Franklin', 'WA', true),('Garfield', 'WA', true),('Grant', 'WA', true),('Grays Harbor', 'WA', true),('Island', 'WA', true),
('Jefferson', 'WA', true),('King', 'WA', true),('Kitsap', 'WA', true),('Kittitas', 'WA', true),('Klickitat', 'WA', true),
('Lewis', 'WA', true),('Lincoln', 'WA', true),('Mason', 'WA', true),('Okanogan', 'WA', true),('Pacific', 'WA', true),
('Pend Oreille', 'WA', true),('Pierce', 'WA', true),('San Juan', 'WA', true),('Skagit', 'WA', true),('Skamania', 'WA', true),
('Snohomish', 'WA', true),('Spokane', 'WA', true),('Stevens', 'WA', true),('Thurston', 'WA', true),('Wahkiakum', 'WA', true),
('Walla Walla', 'WA', true),('Whatcom', 'WA', true),('Whitman', 'WA', true),('Yakima', 'WA', true),
-- West Virginia (55 counties)
('Barbour', 'WV', true),('Berkeley', 'WV', true),('Boone', 'WV', true),('Braxton', 'WV', true),('Brooke', 'WV', true),
('Cabell', 'WV', true),('Calhoun', 'WV', true),('Clay', 'WV', true),('Doddridge', 'WV', true),('Fayette', 'WV', true),
('Gilmer', 'WV', true),('Grant', 'WV', true),('Greenbrier', 'WV', true),('Hampshire', 'WV', true),('Hancock', 'WV', true),
('Hardy', 'WV', true),('Harrison', 'WV', true),('Jackson', 'WV', true),('Jefferson', 'WV', true),('Kanawha', 'WV', true),
('Lewis', 'WV', true),('Lincoln', 'WV', true),('Logan', 'WV', true),('Marion', 'WV', true),('Marshall', 'WV', true),
('Mason', 'WV', true),('McDowell', 'WV', true),('Mercer', 'WV', true),('Mineral', 'WV', true),('Mingo', 'WV', true),
('Monongalia', 'WV', true),('Monroe', 'WV', true),('Morgan', 'WV', true),('Nicholas', 'WV', true),('Ohio', 'WV', true),
('Pendleton', 'WV', true),('Pleasants', 'WV', true),('Pocahontas', 'WV', true),('Preston', 'WV', true),('Putnam', 'WV', true),
('Raleigh', 'WV', true),('Randolph', 'WV', true),('Ritchie', 'WV', true),('Roane', 'WV', true),('Summers', 'WV', true),
('Taylor', 'WV', true),('Tucker', 'WV', true),('Tyler', 'WV', true),('Upshur', 'WV', true),('Wayne', 'WV', true),
('Webster', 'WV', true),('Wetzel', 'WV', true),('Wirt', 'WV', true),('Wood', 'WV', true),('Wyoming', 'WV', true),
-- Wyoming (23 counties)
('Albany', 'WY', true),('Big Horn', 'WY', true),('Campbell', 'WY', true),('Carbon', 'WY', true),('Converse', 'WY', true),
('Crook', 'WY', true),('Fremont', 'WY', true),('Goshen', 'WY', true),('Hot Springs', 'WY', true),('Johnson', 'WY', true),
('Laramie', 'WY', true),('Lincoln', 'WY', true),('Natrona', 'WY', true),('Niobrara', 'WY', true),('Park', 'WY', true),
('Platte', 'WY', true),('Sheridan', 'WY', true),('Sublette', 'WY', true),('Sweetwater', 'WY', true),('Teton', 'WY', true),
('Uinta', 'WY', true),('Washakie', 'WY', true),('Weston', 'WY', true)
ON CONFLICT DO NOTHING;
