/*
  # Populate Counties Table with State Code Data

  ## Overview
  The counties table uses a state_code text column (not a foreign key to a states table).
  This migration inserts all counties for the 4 active service states: TN, MN, WI, KY.

  ## Changes
  1. Inserts Tennessee counties (95 counties) with state_code = 'TN'
  2. Inserts Minnesota counties (87 counties) with state_code = 'MN'
  3. Inserts Wisconsin counties (72 counties) with state_code = 'WI'
  4. Inserts Kentucky counties (120 counties) with state_code = 'KY'
  5. Uses ON CONFLICT DO NOTHING to safely re-run

  ## Notes
  - All counties are marked is_active = true
  - Uses state_code text column directly (no foreign key dependency)
*/

INSERT INTO counties (name, state_code, is_active) VALUES
  ('Anderson', 'TN', true),
  ('Bedford', 'TN', true),
  ('Benton', 'TN', true),
  ('Bledsoe', 'TN', true),
  ('Blount', 'TN', true),
  ('Bradley', 'TN', true),
  ('Campbell', 'TN', true),
  ('Cannon', 'TN', true),
  ('Carroll', 'TN', true),
  ('Carter', 'TN', true),
  ('Cheatham', 'TN', true),
  ('Chester', 'TN', true),
  ('Claiborne', 'TN', true),
  ('Clay', 'TN', true),
  ('Cocke', 'TN', true),
  ('Coffee', 'TN', true),
  ('Crockett', 'TN', true),
  ('Cumberland', 'TN', true),
  ('Davidson', 'TN', true),
  ('Decatur', 'TN', true),
  ('DeKalb', 'TN', true),
  ('Dickson', 'TN', true),
  ('Dyer', 'TN', true),
  ('Fayette', 'TN', true),
  ('Fentress', 'TN', true),
  ('Franklin', 'TN', true),
  ('Gibson', 'TN', true),
  ('Giles', 'TN', true),
  ('Grainger', 'TN', true),
  ('Greene', 'TN', true),
  ('Grundy', 'TN', true),
  ('Hamblen', 'TN', true),
  ('Hamilton', 'TN', true),
  ('Hancock', 'TN', true),
  ('Hardeman', 'TN', true),
  ('Hardin', 'TN', true),
  ('Hawkins', 'TN', true),
  ('Haywood', 'TN', true),
  ('Henderson', 'TN', true),
  ('Henry', 'TN', true),
  ('Hickman', 'TN', true),
  ('Houston', 'TN', true),
  ('Humphreys', 'TN', true),
  ('Jackson', 'TN', true),
  ('Jefferson', 'TN', true),
  ('Johnson', 'TN', true),
  ('Knox', 'TN', true),
  ('Lake', 'TN', true),
  ('Lauderdale', 'TN', true),
  ('Lawrence', 'TN', true),
  ('Lewis', 'TN', true),
  ('Lincoln', 'TN', true),
  ('Loudon', 'TN', true),
  ('McMinn', 'TN', true),
  ('McNairy', 'TN', true),
  ('Macon', 'TN', true),
  ('Madison', 'TN', true),
  ('Marion', 'TN', true),
  ('Marshall', 'TN', true),
  ('Maury', 'TN', true),
  ('Meigs', 'TN', true),
  ('Monroe', 'TN', true),
  ('Montgomery', 'TN', true),
  ('Moore', 'TN', true),
  ('Morgan', 'TN', true),
  ('Obion', 'TN', true),
  ('Overton', 'TN', true),
  ('Perry', 'TN', true),
  ('Pickett', 'TN', true),
  ('Polk', 'TN', true),
  ('Putnam', 'TN', true),
  ('Rhea', 'TN', true),
  ('Roane', 'TN', true),
  ('Robertson', 'TN', true),
  ('Rutherford', 'TN', true),
  ('Scott', 'TN', true),
  ('Sequatchie', 'TN', true),
  ('Sevier', 'TN', true),
  ('Shelby', 'TN', true),
  ('Smith', 'TN', true),
  ('Stewart', 'TN', true),
  ('Sullivan', 'TN', true),
  ('Sumner', 'TN', true),
  ('Tipton', 'TN', true),
  ('Trousdale', 'TN', true),
  ('Unicoi', 'TN', true),
  ('Union', 'TN', true),
  ('Van Buren', 'TN', true),
  ('Warren', 'TN', true),
  ('Washington', 'TN', true),
  ('Wayne', 'TN', true),
  ('Weakley', 'TN', true),
  ('White', 'TN', true),
  ('Williamson', 'TN', true),
  ('Wilson', 'TN', true)
ON CONFLICT (name, state_code) DO NOTHING;

INSERT INTO counties (name, state_code, is_active) VALUES
  ('Aitkin', 'MN', true),
  ('Anoka', 'MN', true),
  ('Becker', 'MN', true),
  ('Beltrami', 'MN', true),
  ('Benton', 'MN', true),
  ('Big Stone', 'MN', true),
  ('Blue Earth', 'MN', true),
  ('Brown', 'MN', true),
  ('Carlton', 'MN', true),
  ('Carver', 'MN', true),
  ('Cass', 'MN', true),
  ('Chippewa', 'MN', true),
  ('Chisago', 'MN', true),
  ('Clay', 'MN', true),
  ('Clearwater', 'MN', true),
  ('Cook', 'MN', true),
  ('Cottonwood', 'MN', true),
  ('Crow Wing', 'MN', true),
  ('Dakota', 'MN', true),
  ('Dodge', 'MN', true),
  ('Douglas', 'MN', true),
  ('Faribault', 'MN', true),
  ('Fillmore', 'MN', true),
  ('Freeborn', 'MN', true),
  ('Goodhue', 'MN', true),
  ('Grant', 'MN', true),
  ('Hennepin', 'MN', true),
  ('Houston', 'MN', true),
  ('Hubbard', 'MN', true),
  ('Isanti', 'MN', true),
  ('Itasca', 'MN', true),
  ('Jackson', 'MN', true),
  ('Kanabec', 'MN', true),
  ('Kandiyohi', 'MN', true),
  ('Kittson', 'MN', true),
  ('Koochiching', 'MN', true),
  ('Lac qui Parle', 'MN', true),
  ('Lake', 'MN', true),
  ('Lake of the Woods', 'MN', true),
  ('Le Sueur', 'MN', true),
  ('Lincoln', 'MN', true),
  ('Lyon', 'MN', true),
  ('McLeod', 'MN', true),
  ('Mahnomen', 'MN', true),
  ('Marshall', 'MN', true),
  ('Martin', 'MN', true),
  ('Meeker', 'MN', true),
  ('Mille Lacs', 'MN', true),
  ('Morrison', 'MN', true),
  ('Mower', 'MN', true),
  ('Murray', 'MN', true),
  ('Nicollet', 'MN', true),
  ('Nobles', 'MN', true),
  ('Norman', 'MN', true),
  ('Olmsted', 'MN', true),
  ('Otter Tail', 'MN', true),
  ('Pennington', 'MN', true),
  ('Pine', 'MN', true),
  ('Pipestone', 'MN', true),
  ('Polk', 'MN', true),
  ('Pope', 'MN', true),
  ('Ramsey', 'MN', true),
  ('Red Lake', 'MN', true),
  ('Redwood', 'MN', true),
  ('Renville', 'MN', true),
  ('Rice', 'MN', true),
  ('Rock', 'MN', true),
  ('Roseau', 'MN', true),
  ('Scott', 'MN', true),
  ('Sherburne', 'MN', true),
  ('Sibley', 'MN', true),
  ('St. Louis', 'MN', true),
  ('Stearns', 'MN', true),
  ('Steele', 'MN', true),
  ('Stevens', 'MN', true),
  ('Swift', 'MN', true),
  ('Todd', 'MN', true),
  ('Traverse', 'MN', true),
  ('Wabasha', 'MN', true),
  ('Wadena', 'MN', true),
  ('Waseca', 'MN', true),
  ('Washington', 'MN', true),
  ('Watonwan', 'MN', true),
  ('Wilkin', 'MN', true),
  ('Winona', 'MN', true),
  ('Wright', 'MN', true),
  ('Yellow Medicine', 'MN', true)
ON CONFLICT (name, state_code) DO NOTHING;

INSERT INTO counties (name, state_code, is_active) VALUES
  ('Adams', 'WI', true),
  ('Ashland', 'WI', true),
  ('Barron', 'WI', true),
  ('Bayfield', 'WI', true),
  ('Brown', 'WI', true),
  ('Buffalo', 'WI', true),
  ('Burnett', 'WI', true),
  ('Calumet', 'WI', true),
  ('Chippewa', 'WI', true),
  ('Clark', 'WI', true),
  ('Columbia', 'WI', true),
  ('Crawford', 'WI', true),
  ('Dane', 'WI', true),
  ('Dodge', 'WI', true),
  ('Door', 'WI', true),
  ('Douglas', 'WI', true),
  ('Dunn', 'WI', true),
  ('Eau Claire', 'WI', true),
  ('Florence', 'WI', true),
  ('Fond du Lac', 'WI', true),
  ('Forest', 'WI', true),
  ('Grant', 'WI', true),
  ('Green', 'WI', true),
  ('Green Lake', 'WI', true),
  ('Iowa', 'WI', true),
  ('Iron', 'WI', true),
  ('Jackson', 'WI', true),
  ('Jefferson', 'WI', true),
  ('Juneau', 'WI', true),
  ('Kenosha', 'WI', true),
  ('Kewaunee', 'WI', true),
  ('La Crosse', 'WI', true),
  ('Lafayette', 'WI', true),
  ('Langlade', 'WI', true),
  ('Lincoln', 'WI', true),
  ('Manitowoc', 'WI', true),
  ('Marathon', 'WI', true),
  ('Marinette', 'WI', true),
  ('Marquette', 'WI', true),
  ('Menominee', 'WI', true),
  ('Milwaukee', 'WI', true),
  ('Monroe', 'WI', true),
  ('Oconto', 'WI', true),
  ('Oneida', 'WI', true),
  ('Outagamie', 'WI', true),
  ('Ozaukee', 'WI', true),
  ('Pepin', 'WI', true),
  ('Pierce', 'WI', true),
  ('Polk', 'WI', true),
  ('Portage', 'WI', true),
  ('Price', 'WI', true),
  ('Racine', 'WI', true),
  ('Richland', 'WI', true),
  ('Rock', 'WI', true),
  ('Rusk', 'WI', true),
  ('St. Croix', 'WI', true),
  ('Sauk', 'WI', true),
  ('Sawyer', 'WI', true),
  ('Shawano', 'WI', true),
  ('Sheboygan', 'WI', true),
  ('Taylor', 'WI', true),
  ('Trempealeau', 'WI', true),
  ('Vernon', 'WI', true),
  ('Vilas', 'WI', true),
  ('Walworth', 'WI', true),
  ('Washburn', 'WI', true),
  ('Washington', 'WI', true),
  ('Waukesha', 'WI', true),
  ('Waupaca', 'WI', true),
  ('Waushara', 'WI', true),
  ('Winnebago', 'WI', true),
  ('Wood', 'WI', true)
ON CONFLICT (name, state_code) DO NOTHING;

INSERT INTO counties (name, state_code, is_active) VALUES
  ('Adair', 'KY', true),
  ('Allen', 'KY', true),
  ('Anderson', 'KY', true),
  ('Ballard', 'KY', true),
  ('Barren', 'KY', true),
  ('Bath', 'KY', true),
  ('Bell', 'KY', true),
  ('Boone', 'KY', true),
  ('Bourbon', 'KY', true),
  ('Boyd', 'KY', true),
  ('Boyle', 'KY', true),
  ('Bracken', 'KY', true),
  ('Breathitt', 'KY', true),
  ('Breckinridge', 'KY', true),
  ('Bullitt', 'KY', true),
  ('Butler', 'KY', true),
  ('Caldwell', 'KY', true),
  ('Calloway', 'KY', true),
  ('Campbell', 'KY', true),
  ('Carlisle', 'KY', true),
  ('Carroll', 'KY', true),
  ('Carter', 'KY', true),
  ('Casey', 'KY', true),
  ('Christian', 'KY', true),
  ('Clark', 'KY', true),
  ('Clay', 'KY', true),
  ('Clinton', 'KY', true),
  ('Crittenden', 'KY', true),
  ('Cumberland', 'KY', true),
  ('Daviess', 'KY', true),
  ('Edmonson', 'KY', true),
  ('Elliott', 'KY', true),
  ('Estill', 'KY', true),
  ('Fayette', 'KY', true),
  ('Fleming', 'KY', true),
  ('Floyd', 'KY', true),
  ('Franklin', 'KY', true),
  ('Fulton', 'KY', true),
  ('Gallatin', 'KY', true),
  ('Garrard', 'KY', true),
  ('Grant', 'KY', true),
  ('Graves', 'KY', true),
  ('Grayson', 'KY', true),
  ('Green', 'KY', true),
  ('Greenup', 'KY', true),
  ('Hancock', 'KY', true),
  ('Hardin', 'KY', true),
  ('Harlan', 'KY', true),
  ('Harrison', 'KY', true),
  ('Hart', 'KY', true),
  ('Henderson', 'KY', true),
  ('Henry', 'KY', true),
  ('Hickman', 'KY', true),
  ('Hopkins', 'KY', true),
  ('Jackson', 'KY', true),
  ('Jefferson', 'KY', true),
  ('Jessamine', 'KY', true),
  ('Johnson', 'KY', true),
  ('Kenton', 'KY', true),
  ('Knott', 'KY', true),
  ('Knox', 'KY', true),
  ('Larue', 'KY', true),
  ('Laurel', 'KY', true),
  ('Lawrence', 'KY', true),
  ('Lee', 'KY', true),
  ('Leslie', 'KY', true),
  ('Letcher', 'KY', true),
  ('Lewis', 'KY', true),
  ('Lincoln', 'KY', true),
  ('Livingston', 'KY', true),
  ('Logan', 'KY', true),
  ('Lyon', 'KY', true),
  ('McCracken', 'KY', true),
  ('McCreary', 'KY', true),
  ('McLean', 'KY', true),
  ('Madison', 'KY', true),
  ('Magoffin', 'KY', true),
  ('Marion', 'KY', true),
  ('Marshall', 'KY', true),
  ('Martin', 'KY', true),
  ('Mason', 'KY', true),
  ('Meade', 'KY', true),
  ('Menifee', 'KY', true),
  ('Mercer', 'KY', true),
  ('Metcalfe', 'KY', true),
  ('Monroe', 'KY', true),
  ('Montgomery', 'KY', true),
  ('Morgan', 'KY', true),
  ('Muhlenberg', 'KY', true),
  ('Nelson', 'KY', true),
  ('Nicholas', 'KY', true),
  ('Ohio', 'KY', true),
  ('Oldham', 'KY', true),
  ('Owen', 'KY', true),
  ('Owsley', 'KY', true),
  ('Pendleton', 'KY', true),
  ('Perry', 'KY', true),
  ('Pike', 'KY', true),
  ('Powell', 'KY', true),
  ('Pulaski', 'KY', true),
  ('Robertson', 'KY', true),
  ('Rockcastle', 'KY', true),
  ('Rowan', 'KY', true),
  ('Russell', 'KY', true),
  ('Scott', 'KY', true),
  ('Shelby', 'KY', true),
  ('Simpson', 'KY', true),
  ('Spencer', 'KY', true),
  ('Taylor', 'KY', true),
  ('Todd', 'KY', true),
  ('Trigg', 'KY', true),
  ('Trimble', 'KY', true),
  ('Union', 'KY', true),
  ('Warren', 'KY', true),
  ('Washington', 'KY', true),
  ('Wayne', 'KY', true),
  ('Webster', 'KY', true),
  ('Whitley', 'KY', true),
  ('Wolfe', 'KY', true),
  ('Woodford', 'KY', true)
ON CONFLICT (name, state_code) DO NOTHING;
