/*
  # Add Wisconsin and Kentucky Counties

  1. Purpose
    - Populate counties for Wisconsin (72 counties)
    - Populate counties for Kentucky (120 counties)
    - Ensures all 4 service states (TN, MN, WI, KY) have complete county data

  2. Data Sources
    - Official state county lists
    - All counties marked as active by default

  3. Changes
    - Inserts all Wisconsin counties linked to WI state
    - Inserts all Kentucky counties linked to KY state
    - Uses ON CONFLICT to safely re-run if needed
*/

-- Get Wisconsin state ID
DO $$
DECLARE
  wi_state_id uuid;
  ky_state_id uuid;
BEGIN
  -- Get Wisconsin state ID
  SELECT id INTO wi_state_id FROM states WHERE code = 'WI';
  
  -- Get Kentucky state ID
  SELECT id INTO ky_state_id FROM states WHERE code = 'KY';

  -- Insert Wisconsin counties (72 counties)
  INSERT INTO counties (name, state_id, is_active) VALUES
    ('Adams', wi_state_id, true),
    ('Ashland', wi_state_id, true),
    ('Barron', wi_state_id, true),
    ('Bayfield', wi_state_id, true),
    ('Brown', wi_state_id, true),
    ('Buffalo', wi_state_id, true),
    ('Burnett', wi_state_id, true),
    ('Calumet', wi_state_id, true),
    ('Chippewa', wi_state_id, true),
    ('Clark', wi_state_id, true),
    ('Columbia', wi_state_id, true),
    ('Crawford', wi_state_id, true),
    ('Dane', wi_state_id, true),
    ('Dodge', wi_state_id, true),
    ('Door', wi_state_id, true),
    ('Douglas', wi_state_id, true),
    ('Dunn', wi_state_id, true),
    ('Eau Claire', wi_state_id, true),
    ('Florence', wi_state_id, true),
    ('Fond du Lac', wi_state_id, true),
    ('Forest', wi_state_id, true),
    ('Grant', wi_state_id, true),
    ('Green', wi_state_id, true),
    ('Green Lake', wi_state_id, true),
    ('Iowa', wi_state_id, true),
    ('Iron', wi_state_id, true),
    ('Jackson', wi_state_id, true),
    ('Jefferson', wi_state_id, true),
    ('Juneau', wi_state_id, true),
    ('Kenosha', wi_state_id, true),
    ('Kewaunee', wi_state_id, true),
    ('La Crosse', wi_state_id, true),
    ('Lafayette', wi_state_id, true),
    ('Langlade', wi_state_id, true),
    ('Lincoln', wi_state_id, true),
    ('Manitowoc', wi_state_id, true),
    ('Marathon', wi_state_id, true),
    ('Marinette', wi_state_id, true),
    ('Marquette', wi_state_id, true),
    ('Menominee', wi_state_id, true),
    ('Milwaukee', wi_state_id, true),
    ('Monroe', wi_state_id, true),
    ('Oconto', wi_state_id, true),
    ('Oneida', wi_state_id, true),
    ('Outagamie', wi_state_id, true),
    ('Ozaukee', wi_state_id, true),
    ('Pepin', wi_state_id, true),
    ('Pierce', wi_state_id, true),
    ('Polk', wi_state_id, true),
    ('Portage', wi_state_id, true),
    ('Price', wi_state_id, true),
    ('Racine', wi_state_id, true),
    ('Richland', wi_state_id, true),
    ('Rock', wi_state_id, true),
    ('Rusk', wi_state_id, true),
    ('St. Croix', wi_state_id, true),
    ('Sauk', wi_state_id, true),
    ('Sawyer', wi_state_id, true),
    ('Shawano', wi_state_id, true),
    ('Sheboygan', wi_state_id, true),
    ('Taylor', wi_state_id, true),
    ('Trempealeau', wi_state_id, true),
    ('Vernon', wi_state_id, true),
    ('Vilas', wi_state_id, true),
    ('Walworth', wi_state_id, true),
    ('Washburn', wi_state_id, true),
    ('Washington', wi_state_id, true),
    ('Waukesha', wi_state_id, true),
    ('Waupaca', wi_state_id, true),
    ('Waushara', wi_state_id, true),
    ('Winnebago', wi_state_id, true),
    ('Wood', wi_state_id, true)
  ON CONFLICT (name, state_id) DO NOTHING;

  -- Insert Kentucky counties (120 counties)
  INSERT INTO counties (name, state_id, is_active) VALUES
    ('Adair', ky_state_id, true),
    ('Allen', ky_state_id, true),
    ('Anderson', ky_state_id, true),
    ('Ballard', ky_state_id, true),
    ('Barren', ky_state_id, true),
    ('Bath', ky_state_id, true),
    ('Bell', ky_state_id, true),
    ('Boone', ky_state_id, true),
    ('Bourbon', ky_state_id, true),
    ('Boyd', ky_state_id, true),
    ('Boyle', ky_state_id, true),
    ('Bracken', ky_state_id, true),
    ('Breathitt', ky_state_id, true),
    ('Breckinridge', ky_state_id, true),
    ('Bullitt', ky_state_id, true),
    ('Butler', ky_state_id, true),
    ('Caldwell', ky_state_id, true),
    ('Calloway', ky_state_id, true),
    ('Campbell', ky_state_id, true),
    ('Carlisle', ky_state_id, true),
    ('Carroll', ky_state_id, true),
    ('Carter', ky_state_id, true),
    ('Casey', ky_state_id, true),
    ('Christian', ky_state_id, true),
    ('Clark', ky_state_id, true),
    ('Clay', ky_state_id, true),
    ('Clinton', ky_state_id, true),
    ('Crittenden', ky_state_id, true),
    ('Cumberland', ky_state_id, true),
    ('Daviess', ky_state_id, true),
    ('Edmonson', ky_state_id, true),
    ('Elliott', ky_state_id, true),
    ('Estill', ky_state_id, true),
    ('Fayette', ky_state_id, true),
    ('Fleming', ky_state_id, true),
    ('Floyd', ky_state_id, true),
    ('Franklin', ky_state_id, true),
    ('Fulton', ky_state_id, true),
    ('Gallatin', ky_state_id, true),
    ('Garrard', ky_state_id, true),
    ('Grant', ky_state_id, true),
    ('Graves', ky_state_id, true),
    ('Grayson', ky_state_id, true),
    ('Green', ky_state_id, true),
    ('Greenup', ky_state_id, true),
    ('Hancock', ky_state_id, true),
    ('Hardin', ky_state_id, true),
    ('Harlan', ky_state_id, true),
    ('Harrison', ky_state_id, true),
    ('Hart', ky_state_id, true),
    ('Henderson', ky_state_id, true),
    ('Henry', ky_state_id, true),
    ('Hickman', ky_state_id, true),
    ('Hopkins', ky_state_id, true),
    ('Jackson', ky_state_id, true),
    ('Jefferson', ky_state_id, true),
    ('Jessamine', ky_state_id, true),
    ('Johnson', ky_state_id, true),
    ('Kenton', ky_state_id, true),
    ('Knott', ky_state_id, true),
    ('Knox', ky_state_id, true),
    ('Larue', ky_state_id, true),
    ('Laurel', ky_state_id, true),
    ('Lawrence', ky_state_id, true),
    ('Lee', ky_state_id, true),
    ('Leslie', ky_state_id, true),
    ('Letcher', ky_state_id, true),
    ('Lewis', ky_state_id, true),
    ('Lincoln', ky_state_id, true),
    ('Livingston', ky_state_id, true),
    ('Logan', ky_state_id, true),
    ('Lyon', ky_state_id, true),
    ('McCracken', ky_state_id, true),
    ('McCreary', ky_state_id, true),
    ('McLean', ky_state_id, true),
    ('Madison', ky_state_id, true),
    ('Magoffin', ky_state_id, true),
    ('Marion', ky_state_id, true),
    ('Marshall', ky_state_id, true),
    ('Martin', ky_state_id, true),
    ('Mason', ky_state_id, true),
    ('Meade', ky_state_id, true),
    ('Menifee', ky_state_id, true),
    ('Mercer', ky_state_id, true),
    ('Metcalfe', ky_state_id, true),
    ('Monroe', ky_state_id, true),
    ('Montgomery', ky_state_id, true),
    ('Morgan', ky_state_id, true),
    ('Muhlenberg', ky_state_id, true),
    ('Nelson', ky_state_id, true),
    ('Nicholas', ky_state_id, true),
    ('Ohio', ky_state_id, true),
    ('Oldham', ky_state_id, true),
    ('Owen', ky_state_id, true),
    ('Owsley', ky_state_id, true),
    ('Pendleton', ky_state_id, true),
    ('Perry', ky_state_id, true),
    ('Pike', ky_state_id, true),
    ('Powell', ky_state_id, true),
    ('Pulaski', ky_state_id, true),
    ('Robertson', ky_state_id, true),
    ('Rockcastle', ky_state_id, true),
    ('Rowan', ky_state_id, true),
    ('Russell', ky_state_id, true),
    ('Scott', ky_state_id, true),
    ('Shelby', ky_state_id, true),
    ('Simpson', ky_state_id, true),
    ('Spencer', ky_state_id, true),
    ('Taylor', ky_state_id, true),
    ('Todd', ky_state_id, true),
    ('Trigg', ky_state_id, true),
    ('Trimble', ky_state_id, true),
    ('Union', ky_state_id, true),
    ('Warren', ky_state_id, true),
    ('Washington', ky_state_id, true),
    ('Wayne', ky_state_id, true),
    ('Webster', ky_state_id, true),
    ('Whitley', ky_state_id, true),
    ('Wolfe', ky_state_id, true),
    ('Woodford', ky_state_id, true)
  ON CONFLICT (name, state_id) DO NOTHING;

END $$;
