/*
  # Replace Florida Markets with Tennessee and Minnesota

  1. Changes
    - Delete all existing Florida county markets
    - Insert all 95 Tennessee counties as markets
    - Insert all 87 Minnesota counties as markets
    
  2. Security
    - Maintains existing RLS policies
    - No changes to permissions
*/

-- Delete existing Florida markets
DELETE FROM markets WHERE state = 'FL';

-- Insert all Tennessee counties
INSERT INTO markets (name, state, is_active) VALUES
  ('Anderson', 'TN', true),
  ('Bedford', 'TN', true),
  ('Benton', 'TN', true),
  ('Bledsoe', 'TN', true),
  ('Blount', 'TN', true),
  ('Bradley', 'TN', true),
  ('Campbell', 'TN', true),
  ('Cannon', 'TN', true),
  ('Carroll', 'TN', true),
  ('Carter', 'TN', true),
  ('Cheatham', 'TN', true),
  ('Chester', 'TN', true),
  ('Claiborne', 'TN', true),
  ('Clay', 'TN', true),
  ('Cocke', 'TN', true),
  ('Coffee', 'TN', true),
  ('Crockett', 'TN', true),
  ('Cumberland', 'TN', true),
  ('Davidson', 'TN', true),
  ('Decatur', 'TN', true),
  ('DeKalb', 'TN', true),
  ('Dickson', 'TN', true),
  ('Dyer', 'TN', true),
  ('Fayette', 'TN', true),
  ('Fentress', 'TN', true),
  ('Franklin', 'TN', true),
  ('Gibson', 'TN', true),
  ('Giles', 'TN', true),
  ('Grainger', 'TN', true),
  ('Greene', 'TN', true),
  ('Grundy', 'TN', true),
  ('Hamblen', 'TN', true),
  ('Hamilton', 'TN', true),
  ('Hancock', 'TN', true),
  ('Hardeman', 'TN', true),
  ('Hardin', 'TN', true),
  ('Hawkins', 'TN', true),
  ('Haywood', 'TN', true),
  ('Henderson', 'TN', true),
  ('Henry', 'TN', true),
  ('Hickman', 'TN', true),
  ('Houston', 'TN', true),
  ('Humphreys', 'TN', true),
  ('Jackson', 'TN', true),
  ('Jefferson', 'TN', true),
  ('Johnson', 'TN', true),
  ('Knox', 'TN', true),
  ('Lake', 'TN', true),
  ('Lauderdale', 'TN', true),
  ('Lawrence', 'TN', true),
  ('Lewis', 'TN', true),
  ('Lincoln', 'TN', true),
  ('Loudon', 'TN', true),
  ('Macon', 'TN', true),
  ('Madison', 'TN', true),
  ('Marion', 'TN', true),
  ('Marshall', 'TN', true),
  ('Maury', 'TN', true),
  ('McMinn', 'TN', true),
  ('McNairy', 'TN', true),
  ('Meigs', 'TN', true),
  ('Monroe', 'TN', true),
  ('Montgomery', 'TN', true),
  ('Moore', 'TN', true),
  ('Morgan', 'TN', true),
  ('Obion', 'TN', true),
  ('Overton', 'TN', true),
  ('Perry', 'TN', true),
  ('Pickett', 'TN', true),
  ('Polk', 'TN', true),
  ('Putnam', 'TN', true),
  ('Rhea', 'TN', true),
  ('Roane', 'TN', true),
  ('Robertson', 'TN', true),
  ('Rutherford', 'TN', true),
  ('Scott', 'TN', true),
  ('Sequatchie', 'TN', true),
  ('Sevier', 'TN', true),
  ('Shelby', 'TN', true),
  ('Smith', 'TN', true),
  ('Stewart', 'TN', true),
  ('Sullivan', 'TN', true),
  ('Sumner', 'TN', true),
  ('Tipton', 'TN', true),
  ('Trousdale', 'TN', true),
  ('Unicoi', 'TN', true),
  ('Union', 'TN', true),
  ('Van Buren', 'TN', true),
  ('Warren', 'TN', true),
  ('Washington', 'TN', true),
  ('Wayne', 'TN', true),
  ('Weakley', 'TN', true),
  ('White', 'TN', true),
  ('Williamson', 'TN', true),
  ('Wilson', 'TN', true);

-- Insert all Minnesota counties
INSERT INTO markets (name, state, is_active) VALUES
  ('Aitkin', 'MN', true),
  ('Anoka', 'MN', true),
  ('Becker', 'MN', true),
  ('Beltrami', 'MN', true),
  ('Benton', 'MN', true),
  ('Big Stone', 'MN', true),
  ('Blue Earth', 'MN', true),
  ('Brown', 'MN', true),
  ('Carlton', 'MN', true),
  ('Carver', 'MN', true),
  ('Cass', 'MN', true),
  ('Chippewa', 'MN', true),
  ('Chisago', 'MN', true),
  ('Clay', 'MN', true),
  ('Clearwater', 'MN', true),
  ('Cook', 'MN', true),
  ('Cottonwood', 'MN', true),
  ('Crow Wing', 'MN', true),
  ('Dakota', 'MN', true),
  ('Dodge', 'MN', true),
  ('Douglas', 'MN', true),
  ('Faribault', 'MN', true),
  ('Fillmore', 'MN', true),
  ('Freeborn', 'MN', true),
  ('Goodhue', 'MN', true),
  ('Grant', 'MN', true),
  ('Hennepin', 'MN', true),
  ('Houston', 'MN', true),
  ('Hubbard', 'MN', true),
  ('Isanti', 'MN', true),
  ('Itasca', 'MN', true),
  ('Jackson', 'MN', true),
  ('Kanabec', 'MN', true),
  ('Kandiyohi', 'MN', true),
  ('Kittson', 'MN', true),
  ('Koochiching', 'MN', true),
  ('Lac qui Parle', 'MN', true),
  ('Lake', 'MN', true),
  ('Lake of the Woods', 'MN', true),
  ('Le Sueur', 'MN', true),
  ('Lincoln', 'MN', true),
  ('Lyon', 'MN', true),
  ('Mahnomen', 'MN', true),
  ('Marshall', 'MN', true),
  ('Martin', 'MN', true),
  ('McLeod', 'MN', true),
  ('Meeker', 'MN', true),
  ('Mille Lacs', 'MN', true),
  ('Morrison', 'MN', true),
  ('Mower', 'MN', true),
  ('Murray', 'MN', true),
  ('Nicollet', 'MN', true),
  ('Nobles', 'MN', true),
  ('Norman', 'MN', true),
  ('Olmsted', 'MN', true),
  ('Otter Tail', 'MN', true),
  ('Pennington', 'MN', true),
  ('Pine', 'MN', true),
  ('Pipestone', 'MN', true),
  ('Polk', 'MN', true),
  ('Pope', 'MN', true),
  ('Ramsey', 'MN', true),
  ('Red Lake', 'MN', true),
  ('Redwood', 'MN', true),
  ('Renville', 'MN', true),
  ('Rice', 'MN', true),
  ('Rock', 'MN', true),
  ('Roseau', 'MN', true),
  ('Scott', 'MN', true),
  ('Sherburne', 'MN', true),
  ('Sibley', 'MN', true),
  ('St. Louis', 'MN', true),
  ('Stearns', 'MN', true),
  ('Steele', 'MN', true),
  ('Stevens', 'MN', true),
  ('Swift', 'MN', true),
  ('Todd', 'MN', true),
  ('Traverse', 'MN', true),
  ('Wabasha', 'MN', true),
  ('Wadena', 'MN', true),
  ('Waseca', 'MN', true),
  ('Washington', 'MN', true),
  ('Watonwan', 'MN', true),
  ('Wilkin', 'MN', true),
  ('Winona', 'MN', true),
  ('Wright', 'MN', true),
  ('Yellow Medicine', 'MN', true);
